# Keymap for yazi
# Default values can be found here:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
#

# Yank to system clipboard and yazi clipboard
[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[manager.append_keymap]]
on   = "<C-m>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
