# Keymap for yazi
# Default values can be found here:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
#
# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
#
[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.append_keymap]]
on   = "<C-m>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
