# Keymap for yazi
# Default values can be found here:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
#

[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", "plugin copy-path" ]
desc = "Yank to yazi clipboard and copy full path to system clipboard"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on   = "<C-m>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
