"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

[mgr]
show_hidden = true

[preview]
wrap = "yes"

[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
    { mime = "text/csv", run = "mlr"},
    # Archive previewer
    { mime = "application/zip",           run = "ouch" },
    { mime = "application/tar",           run = "ouch" },
    { mime = "application/bzip2",         run = "ouch" },
    { mime = "application/7z-compressed", run = "ouch" },
    { mime = "application/rar",           run = "ouch" },
    { mime = "application/xz",            run = "ouch" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
